set_property PACKAGE_PIN W5 [get_ports clk]       
 set_property IOSTANDARD LVCMOS33 [get_ports clk]
#seven-segment LED display
set_property PACKAGE_PIN W7 [get_ports {LED_out[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {LED_out[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {LED_out[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {LED_out[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {LED_out[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {LED_out[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {LED_out[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]

set_property PACKAGE_PIN U2 [get_ports {Anode_Activate[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN U4 [get_ports {Anode_Activate[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {Anode_Activate[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {Anode_Activate[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
   
set_property PACKAGE_PIN V7 [get_ports {dp}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {dp}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports BNTC]						
	set_property IOSTANDARD LVCMOS33 [get_ports BNTC]
set_property PACKAGE_PIN W19 [get_ports BNTL]						
	set_property IOSTANDARD LVCMOS33 [get_ports BNTL]
set_property PACKAGE_PIN T17 [get_ports BNTR]						
	set_property IOSTANDARD LVCMOS33 [get_ports BNTR]
set_property PACKAGE_PIN U17 [get_ports BNTD]						
        set_property IOSTANDARD LVCMOS33 [get_ports BNTD]
        
 ## LEDs
        set_property PACKAGE_PIN U16 [get_ports {empty_slots[0]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[0]}]
        set_property PACKAGE_PIN E19 [get_ports {empty_slots[1]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[1]}]
        set_property PACKAGE_PIN U19 [get_ports {empty_slots[2]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[2]}]
        set_property PACKAGE_PIN V19 [get_ports {empty_slots[3]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[3]}]
        set_property PACKAGE_PIN W18 [get_ports {empty_slots[4]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[4]}]
        set_property PACKAGE_PIN U15 [get_ports {empty_slots[5]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[5]}]
        set_property PACKAGE_PIN U14 [get_ports {empty_slots[6]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[6]}]
#        set_property PACKAGE_PIN V14 [get_ports {empty_slots[7]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[7]}]
#        set_property PACKAGE_PIN V13 [get_ports {empty_slots[8]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[8]}]
#        set_property PACKAGE_PIN V3 [get_ports {empty_slots[9]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[9]}]
#        set_property PACKAGE_PIN W3 [get_ports {empty_slots[10]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[10]}]
#        set_property PACKAGE_PIN U3 [get_ports {empty_slots[11]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[11]}]
#        set_property PACKAGE_PIN P3 [get_ports {empty_slots[12]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[12]}]
#        set_property PACKAGE_PIN N3 [get_ports {empty_slots[13]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[13]}]
#        set_property PACKAGE_PIN P1 [get_ports {empty_slots[14]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[14]}]
#        set_property PACKAGE_PIN L1 [get_ports {empty_slots[15]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {empty_slots[15]}]
 
## Switches
        set_property PACKAGE_PIN V17 [get_ports {Pin[0]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[0]}]
        set_property PACKAGE_PIN V16 [get_ports {Pin[1]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[1]}]
        set_property PACKAGE_PIN W16 [get_ports {Pin[2]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[2]}]
        set_property PACKAGE_PIN W17 [get_ports {Pin[3]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[3]}]
        set_property PACKAGE_PIN W15 [get_ports {Pin[4]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[4]}]
        set_property PACKAGE_PIN V15 [get_ports {Pin[5]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[5]}]
        set_property PACKAGE_PIN W14 [get_ports {Pin[6]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[6]}]
        set_property PACKAGE_PIN W13 [get_ports {Pin[7]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[7]}]
        set_property PACKAGE_PIN V2 [get_ports {Pin[8]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[8]}]
        set_property PACKAGE_PIN T3 [get_ports {Pin[9]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[9]}]
        set_property PACKAGE_PIN T2 [get_ports {Pin[10]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[10]}]
        set_property PACKAGE_PIN R3 [get_ports {Pin[11]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[11]}]
        set_property PACKAGE_PIN W2 [get_ports {Pin[12]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[12]}]
        set_property PACKAGE_PIN U1 [get_ports {Pin[13]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[13]}]
        set_property PACKAGE_PIN T1 [get_ports {Pin[14]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[14]}]
        set_property PACKAGE_PIN R2 [get_ports {Pin[15]}]
        set_property IOSTANDARD LVCMOS33 [get_ports {Pin[15]}]